;;; .user-lisp-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from helheim/word-wrap/autoload.el

(autoload '+word-wrap-mode "helheim/word-wrap/autoload" "\
Wrap long lines in the buffer with language-aware indentation.

This mode configures `adaptive-wrap', `visual-line-mode' and
`visual-fill-column-mode' to wrap long lines without modifying the buffer
content. This is useful when dealing with legacy code which contains
gratuitously long lines, or running emacs on your wrist-phone.

Wrapped lines will be indented to match the preceding line. In code buffers,
lines which are not inside a string or comment will have additional indentation
according to the configuration of `+word-wrap-extra-indent'.

Long lines will wrap at the window margin by default, or can optionally be
wrapped at `fill-column' by configuring `+word-wrap-fill-style'.

This is a minor mode.  If called interactively, toggle the `+Word-Wrap
mode' mode.  If the prefix argument is positive, enable the mode, and if
it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate the variable `+word-wrap-mode'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(put '+global-word-wrap-mode 'globalized-minor-mode t)
(defvar +global-word-wrap-mode nil "\
Non-nil if +Global-Word-Wrap mode is enabled.
See the `+global-word-wrap-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `+global-word-wrap-mode'.")
(custom-autoload '+global-word-wrap-mode "helheim/word-wrap/autoload" nil)
(autoload '+global-word-wrap-mode "helheim/word-wrap/autoload" "\
Toggle +Word-Wrap mode in all buffers.
With prefix ARG, enable +Global-Word-Wrap mode if ARG is positive;
otherwise, disable it.

If called from Lisp, toggle the mode if ARG is `toggle'.
Enable the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

+Word-Wrap mode is enabled in all buffers where
`+word-wrap--enable-global-mode' would do it.

See `+word-wrap-mode' for more information on +Word-Wrap mode.

(fn &optional ARG)" t)
(register-definition-prefixes "helheim/word-wrap/autoload" '("+word-wrap--"))


;;; Generated autoloads from helheim/xref/autoload.el

(autoload 'helheim-xref-find-definitions "helheim/xref/autoload" "\
Find the definition of the identifier at point.

The original `xref-find-definitions' command tries all backends in
`xref-backend-functions' in order to \"find suitable for current context\".
The intended design seems to be that all possible backends for all
major modes are stored in a single global variable, and then `xref-find-backend'
selects an appropriate one.

In practice, however, `xref-find-backend' simply calls each function in
`xref-backend-functions' in order until it finds one that returns a symbol
(`cl-defgeneric' will dispatch on). In practice typical get backend function
looks like this:

  (defun eglot-xref-backend () \"Eglot xref backend.\" 'eglot)

Such functions contain no logic of their own, so Xref always picks the
first backend in the list, and the rest are never tried.  Whoever puts
on the lab coat first becomes the doctor.

This command, in contrast, tries all registered backends in sequence until
the first one succeeds in finding definitions." t)
(autoload 'helheim-xref-find-references "helheim/xref/autoload" "\
Find the references of the identifier at point.
Reed help for `helheim-xref-find-definitions' for the differences from
`xref-find-references'." t)
(autoload 'helheim-xref-find-definitions-other-window "helheim/xref/autoload" "\
Like `helheim-xref-find-definitions' but switch to the other window." t)
(autoload 'helheim-xref-find-definitions-other-frame "helheim/xref/autoload" "\
Like `helheim-xref-find-definitions' but switch to the other frame." t)
(register-definition-prefixes "helheim/xref/autoload" '("helheim-"))


;;; Generated autoloads from helheim/core/helheim-core.el

(register-definition-prefixes "helheim/core/helheim-core" '("ethan/open-" "helheim-" "make-"))


;;; Generated autoloads from helheim/search-and-completion/helheim-corfu.el

(register-definition-prefixes "helheim/search-and-completion/helheim-corfu" '("+corfu-move-to-minibuffer" "corfu-"))


;;; Generated autoloads from helheim/org-mode/helheim-daily-notes.el

(register-definition-prefixes "helheim/org-mode/helheim-daily-notes" '("helheim"))


;;; Generated autoloads from helheim/search-and-completion/deadgrep/helheim-deadgrep.el

(register-definition-prefixes "helheim/search-and-completion/deadgrep/helheim-deadgrep" '("helheim-deadgrep-set-list-buffers-directory-a"))


;;; Generated autoloads from helheim/search-and-completion/deadgrep/helheim-deadgrep-keys.el

(register-definition-prefixes "helheim/search-and-completion/deadgrep/helheim-deadgrep-keys" '("+deadgrep-"))


;;; Generated autoloads from helheim/version-control/helheim-diff-hl.el

(register-definition-prefixes "helheim/version-control/helheim-diff-hl" '("diff-hl-show-hunk-inline"))


;;; Generated autoloads from helheim/dired/helheim-dired.el

(register-definition-prefixes "helheim/dired/helheim-dired" '("helheim-dired-convert-to-global-minor-mode"))


;;; Generated autoloads from helheim/dired/helheim-dired-keys.el

(autoload 'helheim-dired-do-add-id "helheim/dired/helheim-dired-keys" "\
Prepend marked files names with timestamp based ID.
If file already has ID — do nothing." '(dired-mode))
(function-put 'helheim-dired-do-add-id 'interactive-only 't)
(autoload 'helheim-dired-file-id "helheim/dired/helheim-dired-keys" "\
Return FILE's ID if it has one.

(fn FILEPATH)")
(autoload 'helheim-dired-generate-file-id "helheim/dired/helheim-dired-keys" "\
Return ID based on FILE creation time.

(fn FILEPATH)")
(register-definition-prefixes "helheim/dired/helheim-dired-keys" '("+dired-" "dired-subtree-" "helheim-dired-" "image-dired-"))


;;; Generated autoloads from helheim/keybindings/helheim-ediff-keys.el

(autoload 'helheim-ediff-setup-keys "helheim/keybindings/helheim-ediff-keys" "\
Setup Ediff keys.")
(register-definition-prefixes "helheim/keybindings/helheim-ediff-keys" '("helheim-ediff-"))


;;; Generated autoloads from helheim/helheim-edit-indirect.el

(autoload 'helheim-edit-region-indirect "helheim/helheim-edit-indirect" "\
Copy region without text properties, to a separate buffer.
With \\[universal-argument] ask which major mode to use in edit-indirect buffer.

The region is copied, without text properties, to a separate buffer. When done,
exit with `edit-indirect-commit', which will remove the original region and
replace it with the edited version; or with `edit-indirect-abort', which will
drop the modifications.

This differs from `hel-narrow-to-region-indirectly' which clones buffer
inidrectly with narrowing in that the text properties are not shared, so the
parent buffer major mode and the edit-indirect buffer major mode will not be
able to tread on each other's toes by setting up potentially conflicting text
properties, which happens surprisingly often when the font-lock mode is used.

Edit-indirect buffers use the `edit-indirect-mode-map' keymap. Regions with
active edit-indirect buffers use the edit-indirect-overlay-map keymap.

If there's already an edit-indirect buffer for region, use that. If there's
already an edit-indirect buffer active overlapping any portion of region, an
`edit-indirect-overlapping' error is signaled.

(fn ARG)" t)
(register-definition-prefixes "helheim/helheim-edit-indirect" '("helheim-"))


;;; Generated autoloads from helheim/core/helheim-elpaca.el

(register-definition-prefixes "helheim/core/helheim-elpaca" '("elpaca-"))


;;; Generated autoloads from helheim/lang/helheim-emacs-lisp.el

(register-definition-prefixes "helheim/lang/helheim-emacs-lisp" '("helheim-elisp-find-definitions"))


;;; Generated autoloads from helheim/search-and-completion/helheim-embark.el

(register-definition-prefixes "helheim/search-and-completion/helheim-embark" '("hel-embark-select"))


;;; Generated autoloads from helheim/ibuffer/helheim-ibuffer.el

(register-definition-prefixes "helheim/ibuffer/helheim-ibuffer" '("helheim-" "ibuffer-jump"))


;;; Generated autoloads from helheim/version-control/helheim-magit.el

(autoload 'helheim-project-magit "helheim/version-control/helheim-magit" "\
Open Magit status buffer in the current project's root." t)
(register-definition-prefixes "helheim/version-control/helheim-magit" '("helheim-"))


;;; Generated autoloads from helheim/org-mode/helheim-org.el

(register-definition-prefixes "helheim/org-mode/helheim-org" '("ethan/open-" "helheim" "my/org-"))


;;; Generated autoloads from helheim/org-mode/helheim-org-node.el

(register-definition-prefixes "helheim/org-mode/helheim-org-node" '("helheim"))


;;; Generated autoloads from helheim/helheim-outline-mode.el

(register-definition-prefixes "helheim/helheim-outline-mode" '("helheim-outline-"))


;;; Generated autoloads from helheim/helheim-tab-bar.el

(register-definition-prefixes "helheim/helheim-tab-bar" '("helheim-tab-new"))


;;; Generated autoloads from helheim/core/helheim-tree-sitter.el

(register-definition-prefixes "helheim/core/helheim-tree-sitter" '("helheim-install-missing-treesit-grammars"))


;;; Generated autoloads from helheim/word-wrap/helheim-word-wrap.el

(register-definition-prefixes "helheim/word-wrap/helheim-word-wrap" '("+word-wrap-"))


;;; Generated autoloads from prepare-user-lisp.el

(autoload 'prepare-user-lisp "prepare-user-lisp" "\
Byte-compile, scrape autoloads and prepare files in `user-lisp-directory'.
Write the autoload file to AUTOLOAD-FILE. If JUST-ACTIVATE is non-nil,
then the more expensive operations (byte-compilation and autoload
scraping) are skipped, in effect only processing any previous autoloads.
If AUTOLOAD-FILE is nil, store the autoload data in a file next to DIR.
If FORCE is non-nil, or if invoked interactively with a prefix argument,
re-create the entire autoload file and byte-compile everything
unconditionally.

(fn &optional JUST-ACTIVATE AUTOLOAD-FILE FORCE)" t)
(register-definition-prefixes "prepare-user-lisp" '("user-lisp-"))


;;; Generated autoloads from helheim/lang/flycheck_lsp.el

(register-definition-prefixes "helheim/lang/flycheck_lsp" '("lsp-booster--advice-"))


;;; Generated autoloads from helheim/lang/lsp.el

(register-definition-prefixes "helheim/lang/lsp" '("lsp-booster--advice-"))


;;; Generated autoloads from helheim/lang/flycheck-lsp.el

(register-definition-prefixes "helheim/lang/flycheck-lsp" '("lsp-booster--advice-"))


;;; Generated autoloads from helheim/lang/helheim-flycheck-lsp.el

(register-definition-prefixes "helheim/lang/helheim-flycheck-lsp" '("lsp-booster--advice-"))


;;; Generated autoloads from helheim/lang/flycheck_helheim-flycheck-lsp.el

(register-definition-prefixes "helheim/lang/flycheck_helheim-flycheck-lsp" '("lsp-booster--advice-"))


;;; Generated autoloads from helheim/window/helheim-i3.el

(register-definition-prefixes "helheim/window/helheim-i3" '("i3-msg" "my/emacs-i3-"))



;;; Generated autoloads from setup-elisp-utils.el

(register-definition-prefixes "setup-elisp-utils" '("ethan/append-to-list"))


;;; Generated autoloads from setup-ui.el

(register-definition-prefixes "setup-ui" '("display-line-numbers-mode-hook-setup" "ethan/toggle-" "my-linum-inhibit-modes"))


;;; Generated autoloads from setup-latex.el

(register-definition-prefixes "setup-latex" '("czm" "my-" "preview--skip-preamble-region"))


;;; Generated autoloads from setup-bib.el

(register-definition-prefixes "setup-bib" '("my/save-arxiv-to-local-db"))

;;; End of scraped data

(provide '.user-lisp-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; .user-lisp-autoloads.el ends here
